# Copyright (c) 2025 Tareq Mhisen

name: Code Format Check

on:
  workflow_call:

jobs:
  format-check:
    name: Check C and Python Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Install black
        run: pip install black

      - name: Check C Code Formatting
        run: |
          find ./app -name '*.c' -o -name '*.h' | while read file; do
            clang-format --dry-run --Werror "$file"
          done

      - name: Check Python Code Formatting
        run: black --check ./app
